### ISSUE TITLE
Problems with installation of CTGAN

### ISSUE THREAD

**Issue by Zepp3** [sdv-dev/CTGAN#148]
Hi,

I'm trying to install CTGAN but I get the following list of errors:

```
Installing collected packages: scikit-learn, pandas, ctgan
    Running setup.py install for scikit-learn ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\josef\pycharmprojects\ctgan\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\U
sers\\josef\\AppData\\Local\\Temp\\pip-install-uox2ymcw\\scikit-learn_07c9b4c5ccfe446baddb6a64e70aa340\\setup.py'"'"'; **file**='"'"'C:\\Users
\\josef\\AppData\\Local\\Temp\\pip-install-uox2ymcw\\scikit-learn_07c9b4c5ccfe446baddb6a64e70aa340\\setup.py'"'"';f=getattr(tokenize, '"'"'ope
n'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install -
-record 'C:\Users\josef\AppData\Local\Temp\pip-record-6iti0io1\install-record.txt' --single-version-externally-managed --compile --install-hea
ders 'c:\users\josef\pycharmprojects\ctgan\venv\include\site\python3.9\scikit-learn'
         cwd: C:\Users\josef\AppData\Local\Temp\pip-install-uox2ymcw\scikit-learn_07c9b4c5ccfe446baddb6a64e70aa340\
    Complete output (35 lines):
    Partial import of sklearn during the build process.
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\josef\AppData\Local\Temp\pip-install-uox2ymcw\scikit-learn_07c9b4c5ccfe446baddb6a64e70aa340\setup.py", line 303, in <modu
le>
        setup_package()
      File "C:\Users\josef\AppData\Local\Temp\pip-install-uox2ymcw\scikit-learn_07c9b4c5ccfe446baddb6a64e70aa340\setup.py", line 299, in setup
_package
        setup(**metadata)
      File "c:\users\josef\pycharmprojects\ctgan\venv\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\josef\AppData\Local\Temp\pip-install-uox2ymcw\scikit-learn_07c9b4c5ccfe446baddb6a64e70aa340\setup.py", line 182, in confi
guration
        config.add_subpackage('sklearn')
      File "c:\users\josef\pycharmprojects\ctgan\venv\lib\site-packages\numpy\distutils\misc_util.py", line 1019, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "c:\users\josef\pycharmprojects\ctgan\venv\lib\site-packages\numpy\distutils\misc_util.py", line 985, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "c:\users\josef\pycharmprojects\ctgan\venv\lib\site-packages\numpy\distutils\misc_util.py", line 927, in _get_configuration_from_se
tup_py
        config = setup_module.configuration(*args)
      File "sklearn\setup.py", line 86, in configuration
        cythonize_extensions(top_path, config)
      File "C:\Users\josef\AppData\Local\Temp\pip-install-uox2ymcw\scikit-learn_07c9b4c5ccfe446baddb6a64e70aa340\sklearn\_build_utils\__init__
.py", line 50, in cythonize_extensions
        basic_check_build()
      File "C:\Users\josef\AppData\Local\Temp\pip-install-uox2ymcw\scikit-learn_07c9b4c5ccfe446baddb6a64e70aa340\sklearn\_build_utils\pre_buil
d_helpers.py", line 70, in basic_check_build
        compile_test_program(code)
      File "C:\Users\josef\AppData\Local\Temp\pip-install-uox2ymcw\scikit-learn_07c9b4c5ccfe446baddb6a64e70aa340\sklearn\_build_utils\pre_buil
d_helpers.py", line 39, in compile_test_program
        ccompiler.compile(['test_program.c'], output_dir='objects',
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\distutils\_msvccompiler.py", li
ne 323, in compile
        self.initialize()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\distutils\_msvccompiler.py", li
ne 220, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\josef\pycharmprojects\ctgan\venv\lib\site-packages\setuptools\msvc.py", line 313, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "c:\users\josef\pycharmprojects\ctgan\venv\lib\site-packages\setuptools\msvc.py", line 267, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https:
//visualstudio.microsoft.com/visual-cpp-build-tools/


- - -
ERROR: Command errored out with exit status 1: 'c:\users\josef\pycharmprojects\ctgan\venv\scripts\python.exe' -u -c 'import sys, setuptools, t
okenize; sys.argv[0] = '"'"'C:\\Users\\josef\\AppData\\Local\\Temp\\pip-install-uox2ymcw\\scikit-learn_07c9b4c5ccfe446baddb6a64e70aa340\\setup
.py'"'"'; **file**='"'"'C:\\Users\\josef\\AppData\\Local\\Temp\\pip-install-uox2ymcw\\scikit-learn_07c9b4c5ccfe446baddb6a64e70aa340\\setup.py'
"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __fi
le__, '"'"'exec'"'"'))' install --record 'C:\Users\josef\AppData\Local\Temp\pip-record-6iti0io1\install-record.txt' --single-version-externall
y-managed --compile --install-headers 'c:\users\josef\pycharmprojects\ctgan\venv\include\site\python3.9\scikit-learn' Check the logs for full
command output.
```
Can anyone help me there? Thanks ins advance!

**Comment by fealho** [comment]
Hi @Zepp3, if you used `pip` to install it, could you try using `conda` instead? Just run the following command: ```conda install -c sdv-dev -c pytorch -c conda-forge ctgan```.

**Comment by Zepp3** [comment]
Hi @fealho,

thanks for your answer. Unfortunately, It also doesn't work installing with conda ...

**Comment by Zepp3** [comment]
Noticed that one has to be sure to install with python 3.8 when having version 3.9 of python also installed by going with `py -3.8 -m pip install ctgan` (for Windows).
