### ISSUE TITLE
ValueError: could not convert string to float: 'no'

### ISSUE THREAD

**Issue by Zepp3** [sdv-dev/CTGAN#150]
* CTGAN version: v0.4.1 - 2021-03-30
* Python version: 3.8
* Operating System: Windows 10

Hi,

I try to use CTGAN with my dataset which contains columns with strings. CTGAN should handle strings as far as I know but by running it I get the following error:

```
Traceback (most recent call last):
  File "C:/Users/josef/PycharmProjects/CTGAN/main.py", line 20, in <module>
    ctgan.fit(data, discrete_columns)
  File "C:\Users\josef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\ctgan\synthesizers\ctgan.py", line 294, in fit
    self._transformer.fit(train_data, discrete_columns)
  File "C:\Users\josef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\ctgan\data_transformer.py", line 87, in fit
    column_transform_info = self._fit_continuous(
  File "C:\Users\josef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\ctgan\data_transformer.py", line 42, in _fit_continuous
    gm.fit(raw_column_data.reshape(-1, 1))
  File "C:\Users\josef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\mixture\_base.py", line 193, in fit
    self.fit_predict(X, y)
  File "C:\Users\josef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\mixture\_base.py", line 220, in fit_predict
    X = _check_X(X, self.n_components, ensure_min_samples=2)
  File "C:\Users\josef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\mixture\_base.py", line 52, in _check_X
    X = check_array(X, dtype=[np.float64, np.float32],
  File "C:\Users\josef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\josef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\utils\validation.py", line 616, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
  File "C:\Users\josef\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\core\_asarray.py", line 102, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: 'no'

Process finished with exit code 1
```

Can anyone guess what is wrong with the string "no". I tried stripping to be sure no whitespaces are in the dataset but it didn't help.
Thanks in advance!

**Comment by Zepp3** [comment]
I forgot to add the two columns with the `no` strings to the discrete columns. I changed that, now it works.
